run: ./ButtonListener.class
	sudo java -classpath .:classes:/opt/pi4j/lib/'*' ButtonListener 1

compile: ./ButtonListener.java
	javac -classpath .:classes:/opt/pi4j/lib/'*' ButtonListener.java

clean:
	rm *.class
